rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode

before_script:
  - psql -c 'create database postgres_ext_test;' -U postgres
  - cp spec/dummy/config/database.yml.example spec/dummy/config/database.yml

notifications:
  email: 
    - git@danmcclain.net
